/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsIndexRouteImport } from './routes/bots/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as ProtectedProfileRouteImport } from './routes/protected/profile'
import { Route as ProtectedAddServerRouteImport } from './routes/protected/add-server'
import { Route as ProtectedAddBotRouteImport } from './routes/protected/add-bot'
import { Route as BotsBotIdRouteImport } from './routes/bots/$botId'
import { Route as ServersServerIdPublishRouteImport } from './routes/servers/$serverId.publish'
import { Route as ApiSitemapStaticRouteImport } from './routes/api/sitemap/static'
import { Route as ApiSitemapServersRouteImport } from './routes/api/sitemap/servers'
import { Route as ApiSitemapBotsRouteImport } from './routes/api/sitemap/bots'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedBotsBotIdEditRouteImport } from './routes/protected/bots/$botId.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/protected/profile',
  path: '/protected/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAddServerRoute = ProtectedAddServerRouteImport.update({
  id: '/protected/add-server',
  path: '/protected/add-server',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAddBotRoute = ProtectedAddBotRouteImport.update({
  id: '/protected/add-bot',
  path: '/protected/add-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdPublishRoute = ServersServerIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ApiSitemapStaticRoute = ApiSitemapStaticRouteImport.update({
  id: '/api/sitemap/static',
  path: '/api/sitemap/static',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapServersRoute = ApiSitemapServersRouteImport.update({
  id: '/api/sitemap/servers',
  path: '/api/sitemap/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapBotsRoute = ApiSitemapBotsRouteImport.update({
  id: '/api/sitemap/bots',
  path: '/api/sitemap/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBotsBotIdEditRoute = ProtectedBotsBotIdEditRouteImport.update({
  id: '/protected/bots/$botId/edit',
  path: '/protected/bots/$botId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/protected/add-bot': typeof ProtectedAddBotRoute
  '/protected/add-server': typeof ProtectedAddServerRoute
  '/protected/profile': typeof ProtectedProfileRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/bots/': typeof BotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sitemap/bots': typeof ApiSitemapBotsRoute
  '/api/sitemap/servers': typeof ApiSitemapServersRoute
  '/api/sitemap/static': typeof ApiSitemapStaticRoute
  '/servers/$serverId/publish': typeof ServersServerIdPublishRoute
  '/protected/bots/$botId/edit': typeof ProtectedBotsBotIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/protected/add-bot': typeof ProtectedAddBotRoute
  '/protected/add-server': typeof ProtectedAddServerRoute
  '/protected/profile': typeof ProtectedProfileRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/bots': typeof BotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sitemap/bots': typeof ApiSitemapBotsRoute
  '/api/sitemap/servers': typeof ApiSitemapServersRoute
  '/api/sitemap/static': typeof ApiSitemapStaticRoute
  '/servers/$serverId/publish': typeof ServersServerIdPublishRoute
  '/protected/bots/$botId/edit': typeof ProtectedBotsBotIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/protected/add-bot': typeof ProtectedAddBotRoute
  '/protected/add-server': typeof ProtectedAddServerRoute
  '/protected/profile': typeof ProtectedProfileRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/bots/': typeof BotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sitemap/bots': typeof ApiSitemapBotsRoute
  '/api/sitemap/servers': typeof ApiSitemapServersRoute
  '/api/sitemap/static': typeof ApiSitemapStaticRoute
  '/servers/$serverId/publish': typeof ServersServerIdPublishRoute
  '/protected/bots/$botId/edit': typeof ProtectedBotsBotIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/bots/$botId'
    | '/protected/add-bot'
    | '/protected/add-server'
    | '/protected/profile'
    | '/servers/$serverId'
    | '/users/$userId'
    | '/bots/'
    | '/api/auth/$'
    | '/api/sitemap/bots'
    | '/api/sitemap/servers'
    | '/api/sitemap/static'
    | '/servers/$serverId/publish'
    | '/protected/bots/$botId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/bots/$botId'
    | '/protected/add-bot'
    | '/protected/add-server'
    | '/protected/profile'
    | '/servers/$serverId'
    | '/users/$userId'
    | '/bots'
    | '/api/auth/$'
    | '/api/sitemap/bots'
    | '/api/sitemap/servers'
    | '/api/sitemap/static'
    | '/servers/$serverId/publish'
    | '/protected/bots/$botId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/bots/$botId'
    | '/protected/add-bot'
    | '/protected/add-server'
    | '/protected/profile'
    | '/servers/$serverId'
    | '/users/$userId'
    | '/bots/'
    | '/api/auth/$'
    | '/api/sitemap/bots'
    | '/api/sitemap/servers'
    | '/api/sitemap/static'
    | '/servers/$serverId/publish'
    | '/protected/bots/$botId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  ProtectedAddBotRoute: typeof ProtectedAddBotRoute
  ProtectedAddServerRoute: typeof ProtectedAddServerRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
  UsersUserIdRoute: typeof UsersUserIdRoute
  BotsIndexRoute: typeof BotsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSitemapBotsRoute: typeof ApiSitemapBotsRoute
  ApiSitemapServersRoute: typeof ApiSitemapServersRoute
  ApiSitemapStaticRoute: typeof ApiSitemapStaticRoute
  ProtectedBotsBotIdEditRoute: typeof ProtectedBotsBotIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/profile': {
      id: '/protected/profile'
      path: '/protected/profile'
      fullPath: '/protected/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/add-server': {
      id: '/protected/add-server'
      path: '/protected/add-server'
      fullPath: '/protected/add-server'
      preLoaderRoute: typeof ProtectedAddServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/add-bot': {
      id: '/protected/add-bot'
      path: '/protected/add-bot'
      fullPath: '/protected/add-bot'
      preLoaderRoute: typeof ProtectedAddBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId/publish': {
      id: '/servers/$serverId/publish'
      path: '/publish'
      fullPath: '/servers/$serverId/publish'
      preLoaderRoute: typeof ServersServerIdPublishRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/api/sitemap/static': {
      id: '/api/sitemap/static'
      path: '/api/sitemap/static'
      fullPath: '/api/sitemap/static'
      preLoaderRoute: typeof ApiSitemapStaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/servers': {
      id: '/api/sitemap/servers'
      path: '/api/sitemap/servers'
      fullPath: '/api/sitemap/servers'
      preLoaderRoute: typeof ApiSitemapServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/bots': {
      id: '/api/sitemap/bots'
      path: '/api/sitemap/bots'
      fullPath: '/api/sitemap/bots'
      preLoaderRoute: typeof ApiSitemapBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/bots/$botId/edit': {
      id: '/protected/bots/$botId/edit'
      path: '/protected/bots/$botId/edit'
      fullPath: '/protected/bots/$botId/edit'
      preLoaderRoute: typeof ProtectedBotsBotIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServersServerIdRouteChildren {
  ServersServerIdPublishRoute: typeof ServersServerIdPublishRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdPublishRoute: ServersServerIdPublishRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  ProtectedAddBotRoute: ProtectedAddBotRoute,
  ProtectedAddServerRoute: ProtectedAddServerRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
  UsersUserIdRoute: UsersUserIdRoute,
  BotsIndexRoute: BotsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSitemapBotsRoute: ApiSitemapBotsRoute,
  ApiSitemapServersRoute: ApiSitemapServersRoute,
  ApiSitemapStaticRoute: ApiSitemapStaticRoute,
  ProtectedBotsBotIdEditRoute: ProtectedBotsBotIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
