/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsIndexRouteImport } from './routes/bots/index'
import { Route as AddBotIndexRouteImport } from './routes/add-bot/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as BotsBotIdRouteImport } from './routes/bots/$botId'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedAddServerRouteImport } from './routes/_protected/add-server'
import { Route as ServersServerIdPublishRouteImport } from './routes/servers/$serverId.publish'
import { Route as ApiSitemapServersRouteImport } from './routes/api/sitemap/servers'
import { Route as ApiSitemapBotsRouteImport } from './routes/api/sitemap/bots'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBotIndexRoute = AddBotIndexRouteImport.update({
  id: '/add-bot/',
  path: '/add-bot/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAddServerRoute = ProtectedAddServerRouteImport.update({
  id: '/add-server',
  path: '/add-server',
  getParentRoute: () => ProtectedRoute,
} as any)
const ServersServerIdPublishRoute = ServersServerIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ApiSitemapServersRoute = ApiSitemapServersRouteImport.update({
  id: '/api/sitemap/servers',
  path: '/api/sitemap/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapBotsRoute = ApiSitemapBotsRouteImport.update({
  id: '/api/sitemap/bots',
  path: '/api/sitemap/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/add-server': typeof ProtectedAddServerRoute
  '/admin': typeof ProtectedAdminRoute
  '/profile': typeof ProtectedProfileRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/add-bot/': typeof AddBotIndexRoute
  '/bots/': typeof BotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sitemap/bots': typeof ApiSitemapBotsRoute
  '/api/sitemap/servers': typeof ApiSitemapServersRoute
  '/servers/$serverId/publish': typeof ServersServerIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/add-server': typeof ProtectedAddServerRoute
  '/admin': typeof ProtectedAdminRoute
  '/profile': typeof ProtectedProfileRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/add-bot': typeof AddBotIndexRoute
  '/bots': typeof BotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sitemap/bots': typeof ApiSitemapBotsRoute
  '/api/sitemap/servers': typeof ApiSitemapServersRoute
  '/servers/$serverId/publish': typeof ServersServerIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_protected/add-server': typeof ProtectedAddServerRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/add-bot/': typeof AddBotIndexRoute
  '/bots/': typeof BotsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sitemap/bots': typeof ApiSitemapBotsRoute
  '/api/sitemap/servers': typeof ApiSitemapServersRoute
  '/servers/$serverId/publish': typeof ServersServerIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/add-server'
    | '/admin'
    | '/profile'
    | '/bots/$botId'
    | '/servers/$serverId'
    | '/users/$userId'
    | '/add-bot/'
    | '/bots/'
    | '/api/auth/$'
    | '/api/sitemap/bots'
    | '/api/sitemap/servers'
    | '/servers/$serverId/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/add-server'
    | '/admin'
    | '/profile'
    | '/bots/$botId'
    | '/servers/$serverId'
    | '/users/$userId'
    | '/add-bot'
    | '/bots'
    | '/api/auth/$'
    | '/api/sitemap/bots'
    | '/api/sitemap/servers'
    | '/servers/$serverId/publish'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/sitemap.xml'
    | '/_protected/add-server'
    | '/_protected/admin'
    | '/_protected/profile'
    | '/bots/$botId'
    | '/servers/$serverId'
    | '/users/$userId'
    | '/add-bot/'
    | '/bots/'
    | '/api/auth/$'
    | '/api/sitemap/bots'
    | '/api/sitemap/servers'
    | '/servers/$serverId/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BotsBotIdRoute: typeof BotsBotIdRoute
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
  UsersUserIdRoute: typeof UsersUserIdRoute
  AddBotIndexRoute: typeof AddBotIndexRoute
  BotsIndexRoute: typeof BotsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSitemapBotsRoute: typeof ApiSitemapBotsRoute
  ApiSitemapServersRoute: typeof ApiSitemapServersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-bot/': {
      id: '/add-bot/'
      path: '/add-bot'
      fullPath: '/add-bot/'
      preLoaderRoute: typeof AddBotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/add-server': {
      id: '/_protected/add-server'
      path: '/add-server'
      fullPath: '/add-server'
      preLoaderRoute: typeof ProtectedAddServerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/servers/$serverId/publish': {
      id: '/servers/$serverId/publish'
      path: '/publish'
      fullPath: '/servers/$serverId/publish'
      preLoaderRoute: typeof ServersServerIdPublishRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/api/sitemap/servers': {
      id: '/api/sitemap/servers'
      path: '/api/sitemap/servers'
      fullPath: '/api/sitemap/servers'
      preLoaderRoute: typeof ApiSitemapServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/bots': {
      id: '/api/sitemap/bots'
      path: '/api/sitemap/bots'
      fullPath: '/api/sitemap/bots'
      preLoaderRoute: typeof ApiSitemapBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAddServerRoute: typeof ProtectedAddServerRoute
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAddServerRoute: ProtectedAddServerRoute,
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ServersServerIdRouteChildren {
  ServersServerIdPublishRoute: typeof ServersServerIdPublishRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdPublishRoute: ServersServerIdPublishRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BotsBotIdRoute: BotsBotIdRoute,
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
  UsersUserIdRoute: UsersUserIdRoute,
  AddBotIndexRoute: AddBotIndexRoute,
  BotsIndexRoute: BotsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSitemapBotsRoute: ApiSitemapBotsRoute,
  ApiSitemapServersRoute: ApiSitemapServersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
